// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pr1

#ifndef _PR1_UI_H
#define _PR1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
extern int rab;
extern int baran;
extern int baranoff;
extern bool timerActive;
extern int timeoutMinutes;
extern unsigned long timerStartTime;
extern int powerton;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
void ui_event_Roller2(lv_event_t * e);
extern lv_obj_t * ui_Roller2;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Switch2;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_play1_png);    // assets/play1.png
LV_IMG_DECLARE(ui_img_butt_png);    // assets/butt.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
