// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pr1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void button_vkluch(lv_event_t * e);
void button_vikluch(lv_event_t * e);
void timeer_changed(lv_event_t * e);
void poweer_changr(lv_event_t * e);
void konpkatim_off(lv_event_t * e);
void konpkatim_on(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
