// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: pr1
#include "ui.h"
int rab=1;
int baran=0;
int baranoff=1;
int powerton=0;
unsigned long timerStartTime = 0;  // Время старта таймера
int timeoutMinutes = 0;        // Выбранное время в минутах
bool timerActive = false; 
void button_vkluch(lv_event_t * e)
{
	baran=1;
}

void button_vikluch(lv_event_t * e)
{
	baranoff=1;
}

void poweer_changr(lv_event_t * e)
{
	rab=1;
}

void konpkatim_off(lv_event_t * e)
{
	powerton=2;
  timerActive = false;           // Остановить таймер   
}

void konpkatim_on(lv_event_t * e)
{ powerton=1;
	if (timeoutMinutes > 0) {
        timerStartTime = millis();     // Запуск таймера
        timerActive = true;       // Активировать отсчет  
    }
}


void timeer_changed(lv_event_t * e)
{
	lv_obj_t * ui_Roller1 = lv_event_get_target(e);
    char buf[32];
    lv_roller_get_selected_str(ui_Roller1, buf, sizeof(buf));
    timeoutMinutes = atoi(buf);    
}