name: ESP32 Compile Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Update core index
        run: arduino-cli core update-index
      - name: Install ESP32 core
        run: arduino-cli core install esp32:esp32@2.0.16
      - name: Install PCA9557 library
        run: arduino-cli lib install "PCA9557"
      - name: Compile Sketch
        run: arduino-cli compile --fqbn esp32:esp32:esp32 LPG.ino
